config/routes.rb
Rails.application.routes.draw do

root 'people#index'

resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController


  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def edit
    @person = Person.find(params[:id])
  end

 def create
   @person = Person.new(person_params)
    if @person.save
      redirect_to person_path(@person)
    else
      render :new
    end
 end

 def update
   @person = Person.find(params[:id])
     if @person.update(person_params)
       redirect_to person_path(@person)
     else
       render :new
     end
 end

 def destroy
   @person = Person.find(params[:id])
   @person.destroy
   redirect_to people_path
 end

 private
 def person_params
   params.require(:person).permit(:name, :age, :hair_color, :eye_color, :gender, :alive)
 end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
<hr />

<%= form_for @person do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
    <br />

  <%= f.label :age %>
  <%= f.text_field :age %>
  <br />
    <br />

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
  <br />
    <br />

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>
  <br />
    <br />

  <%= f.label :gender %>
  <%= f.text_field :gender %>
  <br />
    <br />

  <%= f.label :alive %>
  <%= f.check_box :alive,{},true,false %>
  <br />
    <br />

  <%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h1> New Person Project</h1>
<hr />

<%= link_to 'Create New Person', new_person_path %>

<% if @people.empty? %>
<h3>No one currently in database. Please create a person.</h3>
<%else%>
<h3>List of People</h3>
  <ul>
      <% @people.each do |person| %>
      <li>
        <%= link_to(person.name, person_path(person)) %>
        <span> - </span>
        <%= link_to 'Edit', edit_person_path(person) %>
        <span> - </span>
        <%= link_to 'Delete', person_path(person), method: :delete%>
      </li>
      <% end%>
    </ul>
<% end %>

app/views/people/new.html.erb
<h1>Create New Person</h1>
<hr />

<%= form_for @person do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <br />

  <%= f.label :age %>
  <%= f.text_field :age %>
  <br />
    <br />

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>
  <br />
    <br />

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>
  <br />
    <br />

  <%= f.label :gender %>
  <%= f.text_field :gender %>
  <br />
    <br />

  <%= f.label :alive %>
  <%= f.check_box :alive,{},true,false %>
  <br />
    <br />

  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1>Person Profile</h1>
<br />


<h1><%=@person.name %>
<ul>
  <li>
    Age: <%= @person.age %>
  </li>

  <li>
    Hair Color: <%= @person.hair_color %>
  </li>

  <li>
    Eye Color: <%= @person.eye_color %>
  </li>

  <li>
    Gender: <%= @person.gender %>
  </li>

  <li>
    Alive: <%= @person.alive %>
  </li>
</ul>



  <i>
    Posted At: <%= @person.created_at %>
  </i>


<br />
  <%= link_to 'Back to Index', people_path %>